# 应用 ID，需修改成自己的应用 ID
id: ${packageId}

# 自定义安装参数，通过 widget 来声明安装表单获取
args:
  - name: app_target
    label: 目标网络
    widget: subnet-select

# 前端模块指定
frontend:
  runtimeMode: console
  src: ./software/frontend/console

# 可调用的云 API
scopes:
  cloudAPI:
    - clb:DescribeLoadBalancers
    - clb:DescribeLoadBalancerOverview
